# Generated by Django 4.1.3 on 2023-05-26 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPSUsernameRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.BooleanField(default=True)),
                ('ps_username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_with_ps_name', to='games.player')),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ps_names_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonOnTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('ev_hp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_atk', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_def', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_spa', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_spd', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_spe', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('iv_hp', models.PositiveIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_atk', models.PositiveIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_def', models.PositiveIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_spa', models.PositiveIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_spd', models.PositiveIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_spe', models.PositiveIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('gigantamax', models.BooleanField(default=False)),
                ('shiny', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Genderless'), ('R', 'Random')], default='R', max_length=1)),
                ('nature', models.CharField(max_length=100, null=True)),
                ('item', models.CharField(max_length=100, null=True)),
                ('ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_ability', to='pokemon.ability')),
                ('move1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move1', to='pokemon.move')),
                ('move2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move2', to='pokemon.move')),
                ('move3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move3', to='pokemon.move')),
                ('move4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move4', to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team_of_pokemon', to='pokemon.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_on_user_team', to='users.userteam')),
                ('tera_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_tera_type', to='pokemon.type')),
            ],
        ),
    ]
