# Generated by Django 4.1.4 on 2023-04-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0003_rename_damage_type_id_typeefficacy_damage_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonOnTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=100)),
                ('ev_hp', models.PositiveIntegerField(default=0)),
                ('ev_atk', models.PositiveIntegerField(default=0)),
                ('ev_def', models.PositiveIntegerField(default=0)),
                ('ev_spa', models.PositiveIntegerField(default=0)),
                ('ev_spd', models.PositiveIntegerField(default=0)),
                ('ev_spe', models.PositiveIntegerField(default=0)),
                ('iv_hp', models.PositiveIntegerField(default=31)),
                ('iv_atk', models.PositiveIntegerField(default=31)),
                ('iv_def', models.PositiveIntegerField(default=31)),
                ('iv_spa', models.PositiveIntegerField(default=31)),
                ('iv_spd', models.PositiveIntegerField(default=31)),
                ('iv_spe', models.PositiveIntegerField(default=31)),
                ('gigantamax', models.BooleanField(default=False)),
                ('shiny', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Genderless'), ('R', 'Random')], default='R', max_length=1)),
                ('ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_ability', to='pokemon.ability')),
                ('move1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move1', to='pokemon.move')),
                ('move2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move2', to='pokemon.move')),
                ('move3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move3', to='pokemon.move')),
                ('move4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move4', to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team_of_pokemon', to='pokemon.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_on_user_team', to='users.userteam')),
                ('tera_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_tera_type', to='pokemon.type')),
            ],
        ),
    ]
