# Generated by Django 4.1.3 on 2023-06-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_teams_of_tier', to='tiers.tier'),
            preserve_default=False,
        ),
    ]
