# Generated by Django 4.1.3 on 2023-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userteam_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
