# Generated by Django 4.1.3 on 2023-05-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpsusernamerelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemononteam',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemononteam',
            name='team',
        ),
        migrations.AddField(
            model_name='pokemononteam',
            name='nature',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userteam',
            name='pokemon1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_team_of_pokemon1', to='users.pokemononteam'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='pokemon2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_team_of_pokemon2', to='users.pokemononteam'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='pokemon3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_team_of_pokemon3', to='users.pokemononteam'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='pokemon4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_team_of_pokemon4', to='users.pokemononteam'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='pokemon5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_team_of_pokemon5', to='users.pokemononteam'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='pokemon6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_team_of_pokemon6', to='users.pokemononteam'),
        ),
    ]
