# Generated by Django 4.1.3 on 2023-06-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
        ('users', '0003_userteam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='name',
            field=models.CharField(default='untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_teams_of_tier', to='tiers.tier'),
        ),
    ]
