# Generated by Django 4.1.3 on 2023-06-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('users', '0004_alter_userteam_name_alter_userteam_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemononteam',
            name='move1',
        ),
        migrations.RemoveField(
            model_name='pokemononteam',
            name='move2',
        ),
        migrations.RemoveField(
            model_name='pokemononteam',
            name='move3',
        ),
        migrations.RemoveField(
            model_name='pokemononteam',
            name='move4',
        ),
        migrations.CreateModel(
            name='MoveOfPokemonOnTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_pokemon_with_move', to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_of_user_pokemon', to='users.pokemononteam')),
            ],
        ),
    ]
