# Generated by Django 4.1.3 on 2023-06-23 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_remove_pokemononteam_move1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_of_ps_username', to='games.player'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='site_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
