# Generated by Django 4.1.3 on 2022-12-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontyperelation',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_of_pokemon', to='pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemontyperelation',
            name='pokemon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_of_type', to='pokemon.type'),
        ),
    ]
