# Generated by Django 4.1.3 on 2023-02-08 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEfficacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_factor', models.PositiveIntegerField()),
                ('damage_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_type', to='pokemon.type')),
                ('target_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targe_type', to='pokemon.type')),
            ],
        ),
    ]
