# Generated by Django 4.1.3 on 2022-12-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemontyperelation_pokemon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='damage_class',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
