# Generated by Django 4.1.3 on 2023-02-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_typeefficacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeefficacy',
            old_name='damage_type_id',
            new_name='damage_type',
        ),
        migrations.RenameField(
            model_name='typeefficacy',
            old_name='target_type_id',
            new_name='target_type',
        ),
    ]
