# Generated by Django 4.1.3 on 2022-12-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_move_damage_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='damage_class',
            field=models.CharField(max_length=100),
        ),
    ]
