# Generated by Django 4.1.3 on 2022-12-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_move_damage_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move_unique_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
