# Generated by Django 4.1.4 on 2023-01-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0001_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('link', models.CharField(max_length=1000, unique=True)),
                ('rating', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.PositiveIntegerField()),
                ('winner', models.BooleanField()),
                ('rating_pre', models.PositiveIntegerField(null=True)),
                ('rating_post', models.PositiveIntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players_in_game', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='MoveUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_that_used_move', to='pokemon.move')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField()),
                ('lead', models.BooleanField()),
                ('evs_hp', models.PositiveIntegerField(default=None, null=True)),
                ('evs_attack', models.PositiveIntegerField(default=None, null=True)),
                ('evs_defense', models.PositiveIntegerField(default=None, null=True)),
                ('evs_special_attack', models.PositiveIntegerField(default=None, null=True)),
                ('evs_special_defense', models.PositiveIntegerField(default=None, null=True)),
                ('evs_speed', models.PositiveIntegerField(default=None, null=True)),
                ('nature', models.CharField(default=None, max_length=100, null=True)),
                ('dynamaxed', models.BooleanField(null=True)),
                ('ability', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_for_used_pokemon', to='pokemon.ability')),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_of_player', to='games.gameplayerrelation')),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_for_used_pokemon', to='pokemon.item')),
                ('moveset', models.ManyToManyField(related_name='pokemon_moveset', through='games.MoveUsage', to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_where_pokemon_used', to='pokemon.pokemon')),
                ('tera_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tera_type_of_pokemon', to='pokemon.type')),
            ],
        ),
        migrations.AddField(
            model_name='moveusage',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_used_by_pokemon', to='games.pokemonusage'),
        ),
        migrations.AddField(
            model_name='gameplayerrelation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_of_player', to='games.player'),
        ),
        migrations.AddField(
            model_name='gameplayerrelation',
            name='team',
            field=models.ManyToManyField(related_name='player_team', through='games.PokemonUsage', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='game_players', through='games.GamePlayerRelation', to='games.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_of_format', to='tiers.tier'),
        ),
        migrations.AlterUniqueTogether(
            name='moveusage',
            unique_together={('pokemon', 'move')},
        ),
        migrations.AlterUniqueTogether(
            name='gameplayerrelation',
            unique_together={('game', 'player')},
        ),
    ]
