# Generated by Django 4.1.3 on 2023-05-26 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('link', models.CharField(max_length=1000, unique=True)),
                ('ranked', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('rating', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.PositiveIntegerField()),
                ('winner', models.BooleanField()),
                ('rating_pre', models.PositiveIntegerField(null=True)),
                ('rating_post', models.PositiveIntegerField(null=True)),
                ('personal_include', models.BooleanField(default=True)),
                ('gathered_by_plugin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoveUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmittedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_by', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField()),
                ('lead', models.BooleanField()),
                ('dynamaxed', models.BooleanField(null=True)),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_of_player', to='games.gameplayerrelation')),
                ('moveset', models.ManyToManyField(related_name='pokemon_moveset', through='games.MoveUsage', to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_where_pokemon_used', to='pokemon.pokemon')),
                ('tera_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tera_type_of_pokemon', to='pokemon.type')),
            ],
        ),
    ]
