# Generated by Django 4.1.3 on 2022-12-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemontyperelation_pokemon_and_more'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='pokemonusage',
            name='game',
        ),
        migrations.RemoveField(
            model_name='pokemonusage',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='game_players', through='games.GamePlayerRelation', to='games.player'),
        ),
        migrations.AddField(
            model_name='gameplayerrelation',
            name='player_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gameplayerrelation',
            name='team',
            field=models.ManyToManyField(related_name='player_team', through='games.PokemonUsage', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='gameplayerrelation',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemonusage',
            name='game_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_in_game', to='games.gameplayerrelation'),
        ),
        migrations.AddField(
            model_name='pokemonusage',
            name='moveset',
            field=models.ManyToManyField(related_name='pokemon_moveset', through='games.MoveUsage', to='pokemon.move'),
        ),
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='gameplayerrelation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players_in_game', to='games.game'),
        ),
        migrations.AlterField(
            model_name='gameplayerrelation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_of_player', to='games.player'),
        ),
        migrations.AlterField(
            model_name='moveusage',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_that_used_move', to='pokemon.move'),
        ),
        migrations.AlterField(
            model_name='moveusage',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_used_by_pokemon', to='games.pokemonusage'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_where_pokemon_used', to='pokemon.pokemon'),
        ),
    ]
