# Generated by Django 4.1.4 on 2023-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='public',
            field=models.BooleanField(),
        ),
    ]
