# Generated by Django 4.1.3 on 2022-12-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_winner_remove_pokemonusage_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerrelation',
            name='player_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gameplayerrelation',
            name='winner',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='game_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_in_game', to='games.gameplayerrelation'),
        ),
    ]
