# Generated by Django 4.1.3 on 2023-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.AddField(
            model_name='game',
            name='ranked',
            field=models.BooleanField(default=True),
        ),
    ]
