# Generated by Django 4.1.3 on 2022-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_pokemonusage_ability_pokemonusage_evs_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonusage',
            name='lead',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='used',
            field=models.BooleanField(),
        ),
    ]
