# Generated by Django 4.1.3 on 2023-03-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_rating_game_ranked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
