# Generated by Django 4.1.3 on 2022-12-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_move_move_unique_name'),
        ('games', '0005_alter_pokemonusage_lead_alter_pokemonusage_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonusage',
            name='ability',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ability_for_used_pokemon', to='pokemon.ability'),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='evs_attack',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='evs_defense',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='evs_hp',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='evs_special_attack',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='evs_special_defense',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='evs_speed',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_for_used_pokemon', to='pokemon.item'),
        ),
        migrations.AlterField(
            model_name='pokemonusage',
            name='nature',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
