# Generated by Django 4.1.3 on 2023-03-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
