# Generated by Django 4.1.3 on 2022-12-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_pokemonusage_ability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayerrelation',
            old_name='post_rating',
            new_name='rating_post',
        ),
        migrations.RenameField(
            model_name='gameplayerrelation',
            old_name='pre_rating',
            new_name='rating_pre',
        ),
    ]
