# Generated by Django 4.1.3 on 2023-03-06 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_usersubmittedgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='site_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='username_of_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersubmittedgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
