# Generated by Django 4.1.3 on 2022-12-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_alter_tier_has_dynamax_alter_tier_has_megas_and_more'),
        ('games', '0008_game_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_of_format', to='tiers.tier'),
        ),
    ]
