# Generated by Django 4.1.4 on 2023-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerrelation',
            name='personal_include',
            field=models.BooleanField(default=True),
        ),
    ]
