# Generated by Django 4.1.3 on 2022-12-09 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_move_move_unique_name'),
        ('games', '0009_alter_game_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonusage',
            name='dynamaxed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pokemonusage',
            name='tera_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tera_type_of_pokemon', to='pokemon.type'),
        ),
    ]
