# Generated by Django 4.1.3 on 2022-12-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_pokemonusage_dynamaxed_pokemonusage_tera_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
