# Generated by Django 4.1.4 on 2023-01-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=100)),
                ('tier_display_name', models.CharField(max_length=100)),
                ('generation', models.PositiveIntegerField()),
                ('style', models.CharField(choices=[('VGC', 'Videogame Championship'), ('SS', 'Smogon Singles'), ('SD', 'Smogon Doubles')], max_length=3)),
                ('has_megas', models.BooleanField(default=False)),
                ('has_zmoves', models.BooleanField(default=False)),
                ('has_dynamax', models.BooleanField(default=False)),
                ('has_tera', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeraWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_tera_type_of_pokemon', to='pokemon.pokemon')),
                ('tera_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_pokemon_of_tera_type', to='pokemon.type')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tera_winrates_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='TeammateWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appearance_rate_lead', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lead_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate_used', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('winrate_lead', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pairing_frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate_winrates_of_pokemon', to='pokemon.pokemon')),
                ('teammate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon6', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate_winrates_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveIntegerField()),
                ('speed_stage', models.IntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speed_tier_of_pokemon', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speed_tiers_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='OpponentWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate_used', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('winrate_lead', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('faceoff_frequency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('faceoff_frequency_lead', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon8', to='pokemon.pokemon')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon7', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opponent_winrates_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='MoveWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('move_frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_percent_damage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon9', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_winrates_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lead_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate_used', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('winrate_lead', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dynamax_frequency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dynamax_winrate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tera_frequency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_winrates_of_pokemon', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_winrates_of_tier', to='tiers.tier')),
            ],
        ),
    ]
