# Generated by Django 4.1.3 on 2022-12-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=100)),
                ('generation', models.PositiveIntegerField()),
                ('style', models.CharField(choices=[('VGC', 'Videogame Championship'), ('SS', 'Smogon Singles'), ('SD', 'Smogon Doubles')], max_length=3)),
                ('has_megas', models.BooleanField()),
                ('has_zmoves', models.BooleanField()),
                ('has_dynamax', models.BooleanField()),
                ('has_tera', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TeammateWinrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon5', to='pokemon.pokemon')),
                ('teammate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon6', to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='OpponentWinrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon8', to='pokemon.pokemon')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon7', to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='MoveWinrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon9', to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualWinrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon4', to='pokemon.pokemon')),
            ],
        ),
    ]
