# Generated by Django 4.1.3 on 2023-05-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWithTeamOrCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_and_cores_of_player', to='games.gameplayerrelation')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonOnTeamOrCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_and_cores_of_pokemon', to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=100)),
                ('tier_display_name', models.CharField(max_length=100)),
                ('generation', models.PositiveIntegerField()),
                ('style', models.CharField(choices=[('VGC', 'Videogame Championship'), ('SS', 'Smogon Singles'), ('SD', 'Smogon Doubles'), ('U', 'Uncategorized')], default='U', max_length=3)),
                ('has_megas', models.BooleanField(default=False)),
                ('has_zmoves', models.BooleanField(default=False)),
                ('has_dynamax', models.BooleanField(default=False)),
                ('has_tera', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeraWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ranked', models.BooleanField(default=False)),
                ('game_count', models.PositiveIntegerField(default=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_tera_type_of_pokemon', to='pokemon.pokemon')),
                ('tera_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_pokemon_of_tera_type', to='pokemon.type')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tera_winrates_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='TeamOrCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_count', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('ranked', models.BooleanField()),
                ('player', models.ManyToManyField(related_name='game_player_with_team_or_core', through='tiers.PlayerWithTeamOrCore', to='games.gameplayerrelation')),
                ('pokemon', models.ManyToManyField(related_name='pokemon_on_team_or_core', through='tiers.PokemonOnTeamOrCore', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_and_cores_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='TeammateWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appearance_rate_lead', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lead_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate_used', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('winrate_lead', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pairing_frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ranked', models.BooleanField(default=False)),
                ('game_count', models.PositiveIntegerField(default=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate_winrates_of_pokemon', to='pokemon.pokemon')),
                ('teammate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon6', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate_winrates_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveIntegerField()),
                ('speed_stage', models.IntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speed_tier_of_pokemon', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speed_tiers_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.AddField(
            model_name='pokemononteamorcore',
            name='team_or_core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_of_team_or_core', to='tiers.teamorcore'),
        ),
        migrations.AddField(
            model_name='playerwithteamorcore',
            name='team_or_core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_with_team_or_core', to='tiers.teamorcore'),
        ),
        migrations.CreateModel(
            name='OpponentWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate_used', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('winrate_lead', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('faceoff_frequency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('faceoff_frequency_lead', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ranked', models.BooleanField(default=False)),
                ('game_count', models.PositiveIntegerField(default=1)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon8', to='pokemon.pokemon')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon7', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opponent_winrates_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='MoveWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('move_frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_percent_damage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ranked', models.BooleanField(default=False)),
                ('game_count', models.PositiveIntegerField(default=1)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon9', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_winrates_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualWinrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lead_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('winrate_used', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('winrate_lead', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dynamax_frequency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dynamax_winrate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tera_frequency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ranked', models.BooleanField(default=False)),
                ('game_count', models.PositiveIntegerField(default=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_winrates_of_pokemon', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_winrates_of_tier', to='tiers.tier')),
            ],
        ),
    ]
