# Generated by Django 4.1.3 on 2023-01-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualwinrate',
            name='winrate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
