# Generated by Django 4.1.3 on 2022-12-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_alter_tier_has_dynamax_alter_tier_has_megas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='tier_display_name',
            field=models.CharField(default='boop', max_length=100),
        ),
    ]
