# Generated by Django 4.1.4 on 2023-02-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_alter_individualwinrate_winrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualwinrate',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movewinrate',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opponentwinrate',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammatewinrate',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terawinrate',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
