# Generated by Django 4.1.3 on 2022-12-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_tier_tier_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='tier_display_name',
            field=models.CharField(max_length=100),
        ),
    ]
