# Generated by Django 4.1.3 on 2022-12-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_move_move_unique_name'),
        ('tiers', '0004_alter_tier_tier_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveIntegerField()),
                ('speed_stage', models.IntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speed_tier_of_pokemon', to='pokemon.pokemon')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speed_tiers_of_tier', to='tiers.tier')),
            ],
        ),
    ]
