# Generated by Django 4.1.4 on 2023-01-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_move_move_unique_name'),
        ('tiers', '0005_speedtier'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualwinrates',
            name='appearance_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='appearance_rate_lead',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='appearance_rate_used',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='dynamax_frequency',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='tera_frequency',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='tier',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.PROTECT, related_name='individual_winrates_of_tier', to='tiers.tier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='winrate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='winrate_lead',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='winrate_used',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movewinrates',
            name='average_percent_damage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='movewinrates',
            name='move_frequency',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movewinrates',
            name='winrate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opponentwinrates',
            name='faceoff_frequency',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opponentwinrates',
            name='tier',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.PROTECT, related_name='opponent_winrates_of_tier', to='tiers.tier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opponentwinrates',
            name='winrate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opponentwinrates',
            name='winrate_lead',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opponentwinrates',
            name='winrate_used',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='appearance_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='appearance_rate_lead',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='appearance_rate_used',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='pairing_frequency',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='tier',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.PROTECT, related_name='teammate_winrates_of_tier', to='tiers.tier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='winrate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='winrate_lead',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='winrate_used',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualwinrates',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_winrates_of_pokemon', to='pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='teammatewinrates',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate_winrates_of_pokemon', to='pokemon.pokemon'),
        ),
        migrations.CreateModel(
            name='TeraWinrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_frequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_tera_type_of_pokemon', to='pokemon.pokemon')),
                ('tera_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_pokemon_of_tera_type', to='pokemon.type')),
            ],
        ),
    ]
