# Generated by Django 4.1.3 on 2023-02-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_rating_game_ranked'),
        ('pokemon', '0003_rename_damage_type_id_typeefficacy_damage_type_and_more'),
        ('tiers', '0005_individualwinrate_game_count_movewinrate_game_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOrCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_count', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('ranked', models.BooleanField()),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_and_cores_of_tier', to='tiers.tier')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonOnTeamOrCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_and_cores_of_pokemon', to='pokemon.pokemon')),
                ('team_or_core', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_of_team_or_core', to='tiers.teamorcore')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWithTeamOrCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_and_cores_of_player', to='games.gameplayerrelation')),
                ('team_or_core', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_with_team_or_core', to='tiers.teamorcore')),
            ],
        ),
    ]
