# Generated by Django 4.1.4 on 2023-01-05 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0006_individualwinrates_appearance_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualwinrates',
            old_name='appearance_rate_lead',
            new_name='lead_rate',
        ),
        migrations.RenameField(
            model_name='individualwinrates',
            old_name='appearance_rate_used',
            new_name='used_rate',
        ),
        migrations.RenameField(
            model_name='teammatewinrates',
            old_name='appearance_rate_used',
            new_name='lead_rate',
        ),
        migrations.AddField(
            model_name='individualwinrates',
            name='dynamax_winrate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='movewinrates',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='move_winrates_of_tier', to='tiers.tier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatewinrates',
            name='used_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terawinrates',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tera_winrates_of_tier', to='tiers.tier'),
            preserve_default=False,
        ),
    ]
