# Generated by Django 4.1.3 on 2023-02-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_rating_game_ranked'),
        ('pokemon', '0003_rename_damage_type_id_typeefficacy_damage_type_and_more'),
        ('tiers', '0006_teamorcore_pokemononteamorcore_playerwithteamorcore'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamorcore',
            name='player',
            field=models.ManyToManyField(related_name='game_player_with_team_or_core', through='tiers.PlayerWithTeamOrCore', to='games.gameplayerrelation'),
        ),
        migrations.AddField(
            model_name='teamorcore',
            name='pokemon',
            field=models.ManyToManyField(related_name='pokemon_on_team_or_core', through='tiers.PokemonOnTeamOrCore', to='pokemon.pokemon'),
        ),
    ]
