# Generated by Django 4.1.4 on 2023-01-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0007_rename_appearance_rate_lead_individualwinrates_lead_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualwinrates',
            name='winrate_lead',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='individualwinrates',
            name='winrate_used',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
