# Generated by Django 4.1.4 on 2023-01-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_move_move_unique_name'),
        ('tiers', '0008_alter_individualwinrates_winrate_lead_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndividualWinrates',
            new_name='IndividualWinrate',
        ),
        migrations.RenameModel(
            old_name='MoveWinrates',
            new_name='MoveWinrate',
        ),
        migrations.RenameModel(
            old_name='OpponentWinrates',
            new_name='OpponentWinrate',
        ),
        migrations.RenameModel(
            old_name='TeammateWinrates',
            new_name='TeammateWinrate',
        ),
        migrations.RenameModel(
            old_name='TeraWinrates',
            new_name='TeraWinrate',
        ),
    ]
