# Generated by Django 4.1.4 on 2023-01-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0009_rename_individualwinrates_individualwinrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opponentwinrate',
            name='winrate_lead',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='opponentwinrate',
            name='winrate_used',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='teammatewinrate',
            name='winrate_lead',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='teammatewinrate',
            name='winrate_used',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
