# Generated by Django 4.1.4 on 2023-01-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0010_alter_opponentwinrate_winrate_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opponentwinrate',
            name='faceoff_frequency_lead',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='opponentwinrate',
            name='faceoff_frequency',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
